/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.granjaagricola.view;

import com.mycompany.granjaagricola.controller.FileHandler;
import com.mycompany.granjaagricola.model.Animales;
import com.mycompany.granjaagricola.model.Cerdos;
import com.mycompany.granjaagricola.model.Gallinas;
import com.mycompany.granjaagricola.model.Granja;
import com.mycompany.granjaagricola.model.Vacas;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fernando
 */
public class FrmAnimales extends javax.swing.JFrame {
    Granja granja = new Granja();
    FileHandler fileHandler = new FileHandler();
    /**
     * Creates new form FrmAnimales
     */
    public FrmAnimales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbIdenficador = new javax.swing.JLabel();
        lbPesoKg = new javax.swing.JLabel();
        lbCantidadTotal = new javax.swing.JLabel();
        lbPrecioComercial = new javax.swing.JLabel();
        txtIdentificador = new javax.swing.JTextField();
        txtPesoKg = new javax.swing.JTextField();
        txtCantidadTotal = new javax.swing.JTextField();
        txtPrecioComercial = new javax.swing.JTextField();
        lbTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lbKilogramosCome = new javax.swing.JLabel();
        txtKilogramosComida = new javax.swing.JTextField();
        lbCantidadAgua = new javax.swing.JLabel();
        txtCantidadAgua = new javax.swing.JTextField();
        lbCantidadHuevos = new javax.swing.JLabel();
        txtCantidadHuevos = new javax.swing.JTextField();
        lbleche = new javax.swing.JLabel();
        rdbLeche = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Animales");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbIdenficador.setText("Identificador");

        lbPesoKg.setText("Peso KG");

        lbCantidadTotal.setText("Cantidad Total");

        lbPrecioComercial.setText("Precio Comercial");

        lbTipo.setText("Tipo Animal");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cerdos", "Gallinas", "Vacas" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        lbKilogramosCome.setText("Kilogramos Comida");

        lbCantidadAgua.setText("Cantidad Agua");

        txtCantidadAgua.setEnabled(false);

        lbCantidadHuevos.setText("Cantidad Huevos");

        txtCantidadHuevos.setEnabled(false);

        lbleche.setText("Leche");

        rdbLeche.setText("Da Leche");
        rdbLeche.setEnabled(false);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnReporte.setText("Reporte");
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbleche)
                        .addGap(96, 96, 96)
                        .addComponent(rdbLeche))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbPrecioComercial)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                            .addComponent(txtPrecioComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lbCantidadTotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantidadTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(lbPesoKg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesoKg, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbIdenficador)
                                    .addGap(59, 59, 59))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbTipo)
                                    .addGap(63, 63, 63)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtIdentificador)
                                .addComponent(cmbTipo, 0, 165, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbKilogramosCome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(btnGuardar))
                                    .addComponent(lbCantidadAgua)
                                    .addComponent(lbCantidadHuevos))
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnReporte))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidadAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtKilogramosComida, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantidadHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIdenficador)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesoKg)
                    .addComponent(txtPesoKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidadTotal)
                    .addComponent(txtCantidadTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPrecioComercial)
                    .addComponent(txtPrecioComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKilogramosComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbKilogramosCome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidadAgua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadHuevos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidadHuevos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbleche)
                    .addComponent(rdbLeche))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnReporte))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        String tipo = (String)cmbTipo.getSelectedItem();
        System.out.println(tipo);
        switch (tipo) {
            case "Cerdos" -> {
                txtCantidadHuevos.setEnabled(false);
                txtCantidadAgua.setEnabled(true);
                txtKilogramosComida.setEnabled(true);
                rdbLeche.setEnabled(false);
            }
            case "Gallinas" -> {
                txtCantidadHuevos.setEnabled(true);
                txtCantidadAgua.setEnabled(false);
                txtKilogramosComida.setEnabled(false);
                rdbLeche.setEnabled(false);
            }
            default -> {
                rdbLeche.setEnabled(true);
                txtCantidadHuevos.setEnabled(false);
                txtCantidadAgua.setEnabled(false);
                txtKilogramosComida.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String tipo = (String)cmbTipo.getSelectedItem();
        
        String identificador = (String)txtIdentificador.getText();
        double pesoKg = Double.parseDouble(txtPesoKg.getText());
        int cantidadTotal = Integer.parseInt(txtCantidadTotal.getText());
        double precioComercial = Double.parseDouble(txtPrecioComercial.getText());
       
        
        switch (tipo) {
            case "Cerdos" -> {
                try {
                    double kilogramosComida = Double.parseDouble(txtKilogramosComida.getText());
                    double cantidadAgua = Double.parseDouble(txtCantidadAgua.getText());
                    Cerdos Cerdos = new Cerdos(kilogramosComida, cantidadAgua, identificador, pesoKg, cantidadTotal, precioComercial);
                    granja.agregarAnimal(Cerdos);
                    fileHandler.agregarAnimales(Cerdos);
                    JOptionPane.showMessageDialog(rootPane, "Animal Guardado");
                    break;
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al Guardar");
                }
            }

            case "Gallinas" -> {
                try {
                    int cantidadHuevos = Integer.parseInt(txtCantidadHuevos.getText());
                    Gallinas gallina = new Gallinas(cantidadHuevos, identificador, pesoKg, cantidadTotal, precioComercial);
                    granja.agregarAnimal(gallina);
                    fileHandler.agregarAnimales(gallina);
                    JOptionPane.showMessageDialog(rootPane, "Animal Guardado");
                    break;
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al Guardar");
                }
            }
            default -> {
                try {
                    boolean daLeche = rdbLeche.isSelected();
                    Vacas vaca = new Vacas(daLeche, identificador, pesoKg, cantidadTotal, precioComercial);
                    granja.agregarAnimal(vaca);
                    fileHandler.agregarAnimales(vaca);
                    JOptionPane.showMessageDialog(rootPane, "Animal Guardado");
                    break;
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Error al Guardar");
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        FrmReporte pantallaReporte = new FrmReporte();
        pantallaReporte.setVisible(true);
        pantallaReporte.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAnimales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAnimales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbCantidadAgua;
    private javax.swing.JLabel lbCantidadHuevos;
    private javax.swing.JLabel lbCantidadTotal;
    private javax.swing.JLabel lbIdenficador;
    private javax.swing.JLabel lbKilogramosCome;
    private javax.swing.JLabel lbPesoKg;
    private javax.swing.JLabel lbPrecioComercial;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbleche;
    private javax.swing.JRadioButton rdbLeche;
    private javax.swing.JTextField txtCantidadAgua;
    private javax.swing.JTextField txtCantidadHuevos;
    private javax.swing.JTextField txtCantidadTotal;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtKilogramosComida;
    private javax.swing.JTextField txtPesoKg;
    private javax.swing.JTextField txtPrecioComercial;
    // End of variables declaration//GEN-END:variables
}
